### ISSUE TITLE
Im : No multipart config for servlet

### ISSUE THREAD

**Issue by mgr9525** [jetty-project/multipartconfig-example#1]
java.lang.IllegalStateException: No multipart config for servlet

help me,thanks!

**Comment by joakime** [comment]
How did you build and run the server?

**Comment by mgr9525** [comment]
I don't build self。
I use "jetty-distribution-9.3.12.v20160915" with "java -jar start.jar" to run.
And just alter "start.ini" - "jetty.http.port".
I test on "windows 10 64"(my computer) could upload,but can't upload on the "Ubuntu server 64".
then,I test on "windows server 2008", because win server have Remote Desktop,so i tested separately from intranet and public network.and found intranet could upload,but public network unable!

I use c# winform HttpWebRequest to upload.

thanks for help,appreciative!

**Comment by mgr9525** [comment]
^ ^,Resolved!
it must set MultipartConfigElement!

thanks!
